name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
env:
  UBUNTU_VERSION: 24.04
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  nvidia-base:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build:
        - {latest: "false", cuda: "12.5.1-base"}
        - {latest: "false", cuda: "12.5.1-runtime"}
        - {latest: "false", cuda: "12.5.1-devel"}

    steps:
      -
        name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      -
        name: Env Setter
        run: |
          echo "PACKAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
      -
        name: Permissions fixes
        run: |
          reponame="$(basename ${GITHUB_REPOSITORY})"
          target="${HOME}/work/${reponame}/${reponame}/build/COPY*"
          chmod -R ug+rwX ${target}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
        with:
          buildkitd-flags: --debug
          driver: docker
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6.4.0
        with:
          context: build
          build-args: |
            IMAGE_BASE=nvidia/cuda:${{ matrix.build.cuda }}-ubuntu${{ env.UBUNTU_VERSION }}
            XPU_TARGET=NVIDIA_GPU
            CUDA_STRING=${{ matrix.build.cuda }}
          push: true
          secrets: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          provenance: false
          no-cache: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/base-image:cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
